#!/bin/bash

#
# Amazon EMR
#
# Copyright 2020, Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Amazon Software License (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#   http://aws.amazon.com/asl/
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.
#

set -e -x

LOG_FILE=/emr/user-role-mapper/log/emr-user-role-mapper.out
PID_FILE=/emr/user-role-mapper/run/emr-user-role-mapper.pid

function start {
    set -x

    EMR_USER_ROLE_MAPPER_HOME="/usr/share/aws/emr/user-role-mapper"
    CLASSPATH="${EMR_USER_ROLE_MAPPER_HOME}/lib/*:/emr/user-role-mapper/conf/:"
    GC_OPTIONS="-XX:+UseGCOverheadLimit -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=\"kill -9 %p\" \
                        -XX:ReservedCodeCacheSize=150M -XX:+PrintCommandLineFlags -XX:+PrintGCDetails \
                        -XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:-UseAdaptiveSizePolicy -XX:MaxTenuringThreshold=15 \
                        -Xloggc:/tmp/emr-user-role-mapper-garbage-collection.log -XX:+PrintFlagsFinal -XX:+UseGCLogFileRotation \
                        -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=128M"

    sudo echo "(console) $(date '+%Y-%m-%d %H:%M:%S') EMR UserRoleMapper start called!" > /dev/console

    LAUNCH_CMD='/usr/bin/java -Xms200m -Xmx1024m '$GC_OPTIONS' -cp '$CLASSPATH' \
        com.amazon.aws.emr.UserRoleMappingServer >> '$LOG_FILE' 2>&1 &'

    sudo -u userrolemapper -H sh -c "$LAUNCH_CMD"

    userrolemapper_pid=$(ps -eo uname:20,pid,cmd | grep "userrolemapper.*[/]usr/bin/java.*emr.UserRoleMappingServer" | awk '{print $2}')
    echo "EMR User Role Mapper process id is $userrolemapper_pid"

    sudo echo $userrolemapper_pid > $PID_FILE

    sleep 5

    echo "(console) $(date '+%Y-%m-%d %H:%M:%S') Listing currently running userrolemapper: " > /dev/console
    echo `ps -efww | grep -i userrolemapper`
}

function stop {
    echo "(console) $(date '+%Y-%m-%d %H:%M:%S') EMR UserRoleMapper stop called!" > /dev/console

    if [[ -f $PID_FILE ]]; then
        userrolemapper_pid=$(cat $PID_FILE)
        kill -9 $userrolemapper_pid
        sudo rm $PID_FILE
    else
        echo "User Role Mapper PID file does not exist. "
    fi
}

function status {
    if [ -e $PID_FILE ] && ps --pid $(cat $PID_FILE) > /dev/null 2>&1 ; then
        echo "EMR User Role Mapper: Running"
        exit 0
    else
        echo "EMR User Role Mapper: Not Running"
        exit 3
    fi
}

if [[ $# -eq 0 ]]; then
    start
else
    case $1 in
        'start' )
            start
            ;;
        'stop' )
            stop
            ;;
        'restart' )
            stop
            start
            ;;
        'status' )
            status
            ;;
        *)
         echo "usage: `basename $0` {start|stop|status}"
    esac
fi

exit 0